# folder where the data is downloaded
data_root: /home/kylin/datasets/scannetpp/scannetpp/data

# Set True to render depth for iphone frames
render_iphone: True
# Set True to render depth for dslr frames
render_dslr: False

splits: [nvs_sem_train, nvs_sem_val]
max_scenes_per_split: 10

# Specify scene ids if you want to render depth for specific scenes
# scene_ids: [355e5e32db]

# The near and far planes for the depth camera during rendering in meters.
near: 0.05
far: 20.0

# Output directory for the rendered depth images. If not given, the output will be saved to data folder in data_root
output_dir: /home/kylin/lyx/project_study/ExCap3D/data/dslr_processed/rendered
