data:
  data_root: /home/kylin/datasets/scannetpp_v2/scannetpp/data

  labels_path: /home/kylin/datasets/scannetpp_v2/scannetpp/metadata/semantic_benchmark/top100.txt
  
  # for instance segmentation
  use_instances: true
  instance_labels_path: /home/kylin/datasets/scannetpp_v2/scannetpp/metadata/semantic_benchmark/top100_instance.txt
  
  ## save multiple labels per vertex/point? ##
  # multilabel:
  #   max_gt: 3
  #   multilabel_only: false

  mapping_file: /home/kylin/datasets/scannetpp_v2/scannetpp/metadata/semantic_benchmark/map_benchmark.csv 
  list_path:  null

  ignore_label: -100

  sample_factor: 1.0

  transforms:
    # read the mesh 
    - add_mesh_vertices
    # map raw labels to benchmark classes
    - map_label_to_index
    # use segments info to get labels on the vertices, handle multilabels
    - get_labels_on_vertices
    # sample points on the mesh and transfer all vertex info to the points
    - sample_points_on_mesh

# dir to save pth training data
out_dir: /home/kylin/lyx/project_study/ExCap3D/data/semantic_processed/semantic_processed_unchunked
