pth_dir: /home/kylin/datasets/scannetpp/scannetpp/data
scene_list: /home/kylin/lyx/project_study/ExCap3D/code/scannetpp/semantic/configs/train.txt

# save in npy format?
save_npy: false
# save in txt format?
save_txt: true

## SEMANTIC
save_semantic: false
sem_out_dir: <out dir for semantic GT>

## INSTANCE
save_instance: false
# save in gt format: sem*1000 + inst id
# save in preds format: 1 file for list of instances, 1 file for each instance 
# same as scannet
inst_gt_format: false
inst_gtformat_out_dir: /home/kylin/lyx/project_study/ExCap3D/data/semantic_processed/semantic_gt_unsampled

inst_preds_format: false
inst_predsformat_out_dir: /home/kylin/lyx/project_study/ExCap3D/data/semantic_processed/semantic_gt_unsampled