
ignore_label: -100
# viz on point cloud? use points from PTH data
viz_pc: true
viz_mesh: false

# use sampled_ or vtx_ properties?
use_sampled: true

# viz on mesh? load mesh separately
data_root: /home/kylin/datasets/scannetpp/scannetpp/data

viz_semantic: true
viz_instances: true

scene_list: /home/kylin/lyx/project_study/ExCap3D/code/scannetpp/semantic/configs/train.txt
pth_dir: /home/kylin/lyx/project_study/ExCap3D/data/semantic_processed/semantic_processed_unchunked
out_dir: /home/kylin/lyx/project_study/ExCap3D/data/semantic_processed/visualized_ply

output_suffix:
  semantic: _gt_sem 
  instance: _gt_inst

palette_path: /home/kylin/lyx/project_study/ExCap3D/code/scannetpp/semantic/configs/palette.txt
